version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: sistemplate-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=sistemplate
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: