version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: sistemplate-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=sistemplate
    volumes:
      - mongodb_data:/data/db
    networks:
      - sistemplate-network

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: sistemplate-zookeeper
    ports:
      - "2181:2181"
    networks:
      - sistemplate-network

  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    container_name: sistemplate-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    depends_on:
      - zookeeper
    networks:
      - sistemplate-network

  sistemplate-app:
    build: .
    container_name: sistemplate-app
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongodb
      - kafka
    networks:
      - sistemplate-network

networks:
  sistemplate-network:
    driver: bridge

volumes:
  mongodb_data: